[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
buidl = "7aiyyKdHw5YTZYJVnQdTskTyQk659fsEqRKu611uBiG5"

[programs.devnet]
buidl = "7aiyyKdHw5YTZYJVnQdTskTyQk659fsEqRKu611uBiG5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/joe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
