[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
buidl = "DBfxok82ngQ6MMHfL2ik5vjCHBDFUePBwsV5N7z4Dd63"

[programs.devnet]
buidl = "DBfxok82ngQ6MMHfL2ik5vjCHBDFUePBwsV5N7z4Dd63"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/joeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
